SOAP FOR XYZ FILES

load and prepare

In [45]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors, rdMolDescriptors
from mordred import Calculator, descriptors
import os
import numpy, math, random
#from visualise import view
from ase import Atoms
import sys
sys.path.insert(0, './data/descriptor_codes/')
sys.path.insert(0, './data/descriptor_codes/src')
from dscribe.descriptors import SOAP

In [63]:
with open('data/1.gfn2.xyz', 'r') as xyz_file:
    lines = xyz_file.readlines()[2:]
atomic_symbols = []
for line in lines:
    atomic_symbols.append(line.split()[0])
import numpy as np
 
atomic_coordinates = np.array([line.split()[1:4] for line in lines], dtype=float)
atomic_symbols1 = set(atomic_symbols)
atomic_symbols1 = list(atomic_symbols1)
print(atomic_symbols1)
print('\n')
print(atomic_coordinates)


['O', 'C', 'N', 'H']


[[-9.2812740e-01  1.3926966e+00 -5.0190000e-04]
 [-1.7228556e+00  2.4414410e-01 -1.8870000e-04]
 [-1.1278776e+00 -1.0205237e+00  3.1700000e-04]
 [ 2.4663630e-01 -1.1413699e+00  3.5030000e-04]
 [ 1.0247464e+00  1.3403200e-02 -1.0360000e-04]
 [ 4.4809080e-01  1.2807039e+00 -4.2290000e-04]
 [ 1.0856487e+00  2.1513617e+00 -7.2130000e-04]
 [ 2.4597585e+00 -1.0507410e-01 -4.1320000e-04]
 [ 2.9413443e+00 -1.2211332e+00 -2.4630000e-04]
 [ 3.1176963e+00  9.1709210e-01  8.4900000e-04]
 [ 7.2950510e-01 -2.1063230e+00  6.3520000e-04]
 [-1.7634930e+00 -1.8926809e+00  5.6820000e-04]
 [-3.1928477e+00  3.6097660e-01 -5.9470000e-04]
 [-3.9600968e+00 -5.6957230e-01  1.2310000e-04]
 [-3.5608860e+00  1.4029221e+00 -4.1700000e-05]
 [-1.3910697e+00  2.3673404e+00 -8.5770000e-04]]


box and soap

In [107]:
calcpos = np.mean(atomic_coordinates, axis=0)
Box = Atoms(
    cell=[
        [100.6402, 0.0, 0.0],
        [0.0, 100.6402, 0.0],
        [0.0, 0.0, 100.6402]
    ],
    positions = atomic_coordinates,
    
    symbols=atomic_symbols,
)


soaper = SOAP(
    r_cut=6,
    n_max=10,
    l_max=10,
    species=atomic_symbols1,
    rbf='gto',
    sparse=False
)

check

In [108]:
soap1 = soaper.create(Box, centers=[calcpos])
#print("Size of descriptor: {}\n".format(soap1.shape[1]))
#print("First five values, for position \n {}: \n{}".format(atomic_coordinates, soap1[0,:5]))
print(soap1[0,:5])

[0.00048816 0.00186274 0.00474998 0.00980216 0.01645807]


In [109]:
print(soap1.shape)

(1, 9020)


In [110]:
print(atomic_coordinates.shape)

(16, 3)
